"""add deleted_at to categories

Revision ID: 5a49acb10b8a
Revises: 60335fccca79
Create Date: 2026-06-16 15:00:10.015933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a49acb10b8a'
down_revision: Union[str, Sequence[str], None] = '60335fccca79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True))
    op.create_index(op.f('ix_categories_deleted_at'), 'categories', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_deleted_at'), table_name='categories')
    op.drop_column('categories', 'deleted_at')
    # ### end Alembic commands ###
