"""add return tracking

Revision ID: 60335fccca79
Revises: d2f8978cfbc0
Create Date: 2026-05-08 16:33:29.849459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60335fccca79'
down_revision: Union[str, Sequence[str], None] = 'd2f8978cfbc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_items', sa.Column('returned_quantity', sa.Integer(), nullable=False))
    op.add_column('sale_items', sa.Column('is_fully_returned', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_items', 'is_fully_returned')
    op.drop_column('sale_items', 'returned_quantity')
    # ### end Alembic commands ###
