"""initial setup

Revision ID: 964bcdcc6676
Revises: 
Create Date: 2026-02-13 11:41:11.563788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '964bcdcc6676'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('business_name', sa.Text(), nullable=False),
    sa.Column('business_type', sa.Text(), server_default='general', nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('contact_number', sa.Text(), nullable=True),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('subscription_start_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('subscription_end_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('total_products', sa.Integer(), server_default='0', nullable=True),
    sa.Column('out_of_stock_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('low_stock_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('last_active_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
