"""add business_type to users

Revision ID: b2ec524123b5
Revises: 0e64429605dc
Create Date: 2026-01-27 14:53:37.150935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2ec524123b5'
down_revision: Union[str, Sequence[str], None] = '0e64429605dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('business_type', sa.Text(), nullable=False))
    op.add_column('users', sa.Column('name', sa.Text(), nullable=False))
    op.add_column('users', sa.Column('contact_number', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('notifications_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('subscription_start_date', sa.TIMESTAMP(), nullable=True))
    op.add_column('users', sa.Column('subscription_end_date', sa.TIMESTAMP(), nullable=True))
    op.add_column('users', sa.Column('total_products', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('out_of_stock_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('low_stock_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_active_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True))
    op.alter_column('users', 'business_name',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'role')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('users', 'business_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'last_active_at')
    op.drop_column('users', 'low_stock_count')
    op.drop_column('users', 'out_of_stock_count')
    op.drop_column('users', 'total_products')
    op.drop_column('users', 'subscription_end_date')
    op.drop_column('users', 'subscription_start_date')
    op.drop_column('users', 'notifications_enabled')
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'contact_number')
    op.drop_column('users', 'name')
    op.drop_column('users', 'business_type')
    # ### end Alembic commands ###
