"""updated models structure

Revision ID: bcb03d3d8a79
Revises: 964bcdcc6676
Create Date: 2026-02-14 12:33:38.941223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bcb03d3d8a79'
down_revision: Union[str, Sequence[str], None] = '964bcdcc6676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider_subscription_id', sa.Text(), nullable=False),
    sa.Column('provider_payment_id', sa.Text(), nullable=True),
    sa.Column('subscription_plan', sa.Enum('free', 'starter', 'pro', name='subscription_plan_enum'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'cancelled', 'expired', 'failed', name='payment_status_enum'), nullable=False),
    sa.Column('current_period_end', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_status', 'payments', ['status'], unique=False)
    op.create_index('ix_payments_user_id', 'payments', ['user_id'], unique=False)
    op.alter_column('categories', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
    op.drop_constraint(op.f('categories_user_id_fkey'), 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('category_fields', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('category_fields', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.create_index(op.f('ix_category_fields_category_id'), 'category_fields', ['category_id'], unique=False)
    op.alter_column('jobs', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('jobs_user_id_fkey'), 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_products_category_id', 'products', ['category_id'], unique=False)
    op.create_index('ix_products_deleted_at', 'products', ['deleted_at'], unique=False)
    op.create_index('ix_products_user_id', 'products', ['user_id'], unique=False)
    op.drop_constraint(op.f('products_category_id_fkey'), 'products', type_='foreignkey')
    op.drop_constraint(op.f('products_user_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.alter_column('sales', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_sales_product_id', 'sales', ['product_id'], unique=False)
    op.create_index('ix_sales_user_id', 'sales', ['user_id'], unique=False)
    op.drop_constraint(op.f('sales_product_id_fkey'), 'sales', type_='foreignkey')
    op.drop_constraint(op.f('sales_user_id_fkey'), 'sales', type_='foreignkey')
    op.create_foreign_key(None, 'sales', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sales', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('teams', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index('ix_teams_user_id', 'teams', ['user_id'], unique=False)
    op.drop_constraint(op.f('teams_user_id_fkey'), 'teams', type_='foreignkey')
    op.create_foreign_key(None, 'teams', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'notifications_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'total_products',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'out_of_stock_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'low_stock_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_users_deleted_at', 'users', ['deleted_at'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_deleted_at', table_name='users')
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'low_stock_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'out_of_stock_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'total_products',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'notifications_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.create_foreign_key(op.f('teams_user_id_fkey'), 'teams', 'users', ['user_id'], ['id'])
    op.drop_index('ix_teams_user_id', table_name='teams')
    op.alter_column('teams', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.create_foreign_key(op.f('sales_user_id_fkey'), 'sales', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('sales_product_id_fkey'), 'sales', 'products', ['product_id'], ['id'])
    op.drop_index('ix_sales_user_id', table_name='sales')
    op.drop_index('ix_sales_product_id', table_name='sales')
    op.alter_column('sales', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_user_id_fkey'), 'products', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('products_category_id_fkey'), 'products', 'categories', ['category_id'], ['id'])
    op.drop_index('ix_products_user_id', table_name='products')
    op.drop_index('ix_products_deleted_at', table_name='products')
    op.drop_index('ix_products_category_id', table_name='products')
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key(op.f('jobs_user_id_fkey'), 'jobs', 'users', ['user_id'], ['id'])
    op.alter_column('jobs', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_category_fields_category_id'), table_name='category_fields')
    op.alter_column('category_fields', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.alter_column('category_fields', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key(op.f('categories_user_id_fkey'), 'categories', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
    op.alter_column('categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.alter_column('categories', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('ix_payments_user_id', table_name='payments')
    op.drop_index('ix_payments_status', table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
