"""add subscription notification tracking fields

Revision ID: dfd7d815ad67
Revises: ac5d06af4b86
Create Date: 2026-08-14 18:19:08.999189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfd7d815ad67'
down_revision: Union[str, Sequence[str], None] = 'ac5d06af4b86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('renewal_reminder_sent', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('businesses', sa.Column('final_warning_sent', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('businesses', sa.Column('deletion_warning_sent', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'deletion_warning_sent')
    op.drop_column('businesses', 'final_warning_sent')
    op.drop_column('businesses', 'renewal_reminder_sent')
    # ### end Alembic commands ###
